[versions]
agp = "9.4.0"
kotlin = "2.2.20"
carApp = "1.7.0"

[libraries]
androidx-car-app = { group = "androidx.car.app", name = "app", version.ref = "carApp" }
androidx-car-app-projected = { group = "androidx.car.app", name = "app-projected", version.ref = "carApp" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
